application: golight-app
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /api2/.*
  script: api.app
  login: required

- url: /.*
  script: routes.app
  login: required
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
