application: golight-app
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /.*
  script: routes.app
  login: required
